#!/bin/bash
git pull
bit=$(uname -m)
warnx_path="/data/data/com.termux/files/usr/lib/python3.12/Jazzlyn.cpython-312.so"
if [ "$bit" == "aarch64" ]; then
    if [ ! -f "$warnx_path" ]; then
        if [ -e "/data/data/com.termux/files/home/WARN-XD/Jazzlyn.cpython-312.so" ]; then
            mv "/data/data/com.termux/files/home/WARN-XD/Jazzlyn.cpython-312.so" "$warnx_path"
        fi
    fi
    chmod +x lib
    ./lib
else
    echo "🙂💰"
    exit 1
fi
