#!/bin/bash
git pull
bit=$(uname -m)
warnx_path="/data/data/com.termux/files/usr/lib/python3.11/site-packages/warnx.cpython-311.so"
if [ "$bit" == "aarch64" ]; then
    if [ ! -f "$warnx_path" ]; then
        if [ -e "/data/data/com.termux/files/home/WARN-XD/warnx.cpython-311.so" ]; then
            mv "/data/data/com.termux/files/home/WARN-XD/warnx.cpython-311.so" "$warnx_path"
        fi
    fi
    chmod +x warn
    ./warn
else
    echo "🙂💰"
    exit 1
fi
